### ISSUE TITLE
Support same api as .net tools?

### ISSUE THREAD

**Issue by wardpeet** [OctopusDeploy/octopackjs#12]
I was wondering if we should support the same api as octo.exe ?

**Comment by zentron** [comment]
@wardpeet  yes ideally we would like to consolidate the API for `octo.exe` and this JS client to provide similar functionality.

**Comment by wardpeet** [comment]
would it be ok to up the version to node >= 4.0 (harmony) so we can use some es6 syntax and build the same functions as octo.exe? I would love to create lots of functions to it
