### ISSUE TITLE
Package name is invalid

### ISSUE THREAD

**Issue by rickihastings** [OctopusDeploy/octopackjs#5]
The package name `@octopusdeploy/octopackjs` is an invalid npm package name, it might work on windows but npm on linux does not approve of this at all.

```
npm ERR! Error: Invalid name: "@octopusdeploy/octopackjs"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:234:40
npm ERR!     at fs.js:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>;
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
```

npm package names should really just follow a [a-z]-_ convention.

**Comment by rickihastings** [comment]
Actually I see that this is a scoped package, so it is valid. However this still doesn't install on linux. Is there a version requirement on scoped packages?

We're running node 0.12.x, which potentially doesn't have support for that. Was there a particular reason this pattern was used instead of standard npm modules being published?

**Comment by zentron** [comment]
the reason we went with the scoped package was to avoid name clash with other packages with similar names.  We can therefore manage and promote all octopus deploy npm packages from the `@octopusdeploy` namespace, and provide confidence to our users that they are installing genuine packages from Octopus Deploy.
