### ISSUE TITLE
octo.push fails with "Missing error message".

### ISSUE THREAD

**Issue by pgobbato** [OctopusDeploy/octopackjs#7]
I am setting up octopackjs through jenkins.  Using gulp-octo, I am packing and then pushing.  

It is failing on the following line in gulpfile.js:

`.pipe(octo.push({apiKey: 'API-SUPERCOOLAPIKEY', host: 'https://octopus.buildserv.ourdomain.net'}));`

I attached the console output from jenkins.  Why is this failing?  I suspect it has to do with SSH, but the error message is less than helpful.  Thanks!

[pushfail.txt](https://github.com/OctopusDeploy/octopackjs/files/318955/pushfail.txt)

**Comment by MacsDickinson** [comment]
I'm getting this too. Here's my gulp script

``` javascript
const gulp = require('gulp');
const bump = require('gulp-bump');
const octo = require('@octopusdeploy/gulp-octo');

gulp.task('bump', () =>
  gulp.src('./package.json')
      .pipe(bump({ version: '1.1.1' }))
      .pipe(gulp.dest('./'))
);

gulp.task('publish', ['bump'], () =>
  gulp.src(['**/*', '!bin{,/**}', '!src{,/**}', '!gulpfile.js'])
      .pipe(octo.pack())
      .pipe(octo.push({
        apiKey: 'http://myserver',
        host: 'API-MYKEY'
      }))
);
```

**Comment by MacsDickinson** [comment]
My API key and host are the wrong way around 😞 

I added a console.log to gulp-octo which led me to this. Looks like the issue here is that `gulp-octo` isn't passing the error back to gulp nicely

**Comment by zentron** [comment]
Thanks for the update @MacsDickinson . Will look at adding a fix to the backlog

**Comment by gpltaylor** [comment]
I have also come across this where I miss-typed my domain name. If it's not able to resolve then the error is not returned and triggers the helpful "Missing error message".

**Comment by zentron** [comment]
This was an issue with `gulp-octo` not passing through the error and is now fixed in https://github.com/OctopusDeploy/gulp-octo/commit/61047bf924eb47eec20d9486ee2609a424c3f8cf
